imports:
    - { resource: config_dev.yml }

# this cache is used during tests when setting up pimcore
pimcore:
    cache:
        pool_service_id: pimcore.cache.core.pool.array

doctrine:
    dbal:
        connections:
            default:
                url: ~
                host: 127.0.0.1
                port: ~
                dbname: pimcore_devkit_test
                user: travis
                password: ~
